[package]
name = "miso_record_shop"
edition = "2024"
license = "Apache-2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
miso = { git = "https://github.com/misofm/protocol.git", rev = "ffa0e38b8ba4815d81de1076101ea37d2c71c623" }
miso_record = { git = "https://github.com/misofm/record.git", rev = "2ae6ab937752d9cc83a70d1cf78bde90f564a438" }
